// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ldipdduhdpeugwvxjbrr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxkaXBkZHVoZHBldWd3dnhqYnJyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0MDIyMjQsImV4cCI6MjA2MTk3ODIyNH0.7JtcrzPIZjFAGwdJfLgTdLr8vUtSkLvGalF1J3iqPjs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});